### ISSUE TITLE
Code & Data

### ISSUE THREAD

**Issue by candacelax** [behavioral-data/Empathy-Mental-Health#1]
Just read the work, awesome paper! When do you think the model and data will be available?

**Comment by ash-shar** [comment]
Hey, thanks so much for your interest in our work. We plan to release all codes and models next week. We expect to release a part of our dataset next week and the remaining dataset sometime in October. 

Feel free to reach out if there are any questions. Thanks!

**Comment by candacelax** [comment]
Good to know, thanks Ashish!
