### ISSUE TITLE
Request of the rationale extractor implementation 

### ISSUE THREAD

**Issue by yehchunhung** [behavioral-data/Empathy-Mental-Health#10]
In the paper, the model consists of the empathy identifier and the rationale extractor. However, in [test.py](https://github.com/behavioral-data/Empathy-Mental-Health/blob/92f13509af90d0725ef8d8f4ff52fdaab5d3758e/src/test.py), you only have `EmpathyClassifier` to predict the levels of emotional reaction, interpretation, and exploration. Thus, I would like to know if the authors could release the implementation of the rationale extractor and augment it to [test.py](https://github.com/behavioral-data/Empathy-Mental-Health/blob/92f13509af90d0725ef8d8f4ff52fdaab5d3758e/src/test.py).

I look forward to your reply.

**Comment by ash-shar** [comment]
Hi @yehchunhung,

Extremely sorry for the very slow reply. Haven't been following the issues on this repository of late.

We have now added the code for extracting rationales. Hope that helps and thanks a lot for pointing out this issue

Thanks!
