### ISSUE TITLE
about talklife data

### ISSUE THREAD

**Issue by A-Rain** [behavioral-data/Empathy-Mental-Health#3]
Hi, I just read your paper and this is a very remarkable work. While I only find reddit data in `./dataset`. Could you please provide `talklife` data? my email is ` rain.yuhan@foxmail.com`

thanks

**Comment by ash-shar** [comment]
Hi,

Thank you for your interest! As described in the readme, for accessing the TalkLife portion of our dataset for non-commercial use, please contact the TalkLife team at research@talklife.co

Thanks!
