### ISSUE TITLE
Data requestion

### ISSUE THREAD

**Issue by SihengLi99** [behavioral-data/Empathy-Mental-Health#7]
Hi,

This is a great job, by the way, can you share the Mental Health Subreddits data (55 mental health focused subreddits, 8M interactions as mentioned in the paper) for me ?

If possible, you can share me through:  
sihengli99.11.10@gmail.com

**Comment by ash-shar** [comment]
Hi,

Thank you for your interest in our dataset!

We had collected this dataset based on the list of mental health subreddits in this paper: https://www.ccis.northeastern.edu/home/evasharma/papers/CHI2018_SupportSharma.pdf

I would recommend using either pushshift.io (https://pushshift.io/api-parameters/) or Google Big Query (https://console.cloud.google.com/bigquery) for directly accessing this dataset. I will check back with the team if we can share this over email.

Thanks!

**Comment by SihengLi99** [comment]
> Hi,
> 
> Thank you for your interest in our dataset!
> 
> We had collected this dataset based on the list of mental health subreddits in this paper: https://www.ccis.northeastern.edu/home/evasharma/papers/CHI2018_SupportSharma.pdf
> 
> I would recommend using either pushshift.io (https://pushshift.io/api-parameters/) or Google Big Query (https://console.cloud.google.com/bigquery) for directly accessing this dataset. I will check back with the team if we can share this over email.
> 
> Thanks!

Sincerely Thank you ！
